
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.CallableStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Quan_Ly_Lich_Lam_Viec extends javax.swing.JFrame {

    /**
     * Creates new form Quan_Ly_Lich_Lam_Viec
     */
    
    DefaultTableModel tableModel;
    
    public Quan_Ly_Lich_Lam_Viec() {
        initComponents();
                        
        tableModel = (DefaultTableModel) jTable1.getModel();
        
        Connection conn = null;
        Statement stmt = null;
        List<lichlamviec> llv = new ArrayList<>();
        List<calam> cl = new ArrayList<>();
        
        try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        conn = DriverManager.getConnection("jdbc:mysql://localhost/quantridulieu?"

        + "user=root");
        
        stmt=conn.createStatement();
        
        String sql="select * from lichlamviec order by thu";
        ResultSet rs = stmt.executeQuery(sql);
        
        
        while(rs.next()){
            lichlamviec l = new lichlamviec(rs.getString("thu"),
                    rs.getInt("idnv"),
                    rs.getInt("idcalam")
                    );
            llv.add(l);
        }
                
        String sql1="select * from calam";
        ResultSet rs1 = stmt.executeQuery(sql1);
        
        
        while(rs1.next()){
            calam c = new calam(rs1.getInt("idcalam"),
                    rs1.getDouble("hesoluong"),
                    rs1.getTime("giobatdau"),
                    rs1.getTime("gioketthuc"));                 
            cl.add(c);
        }

        } catch (Exception ex) { //xử lý ngoại lệ nếu có
        ex.printStackTrace();
        }
        
        finally {
            //giải phóng tài nguyên khi không sử dụng nữa
            if (stmt != null) {
            try {
            stmt.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            stmt = null;
            }

            if (conn != null) {
            try {
            conn.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            conn = null;
            }}
        System.out.println("Size: "+llv.size());
        for(lichlamviec l : llv){
            System.out.println(l);
            
            tableModel.addRow(new Object[]{
               
               l.getThu(),l.getIdnv(),l.getIdcl()
            });
        }
        
        tableModel = (DefaultTableModel) jTable2.getModel();
        
        for(calam c : cl){
            System.out.println(c);
            
            tableModel.addRow(new Object[]{
               
               c.getIdcl(),c.getHesoluong(),c.getGiobatdau(),c.getGioketthuc()
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdnv = new javax.swing.JTextField();
        txtIdcl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtThu = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnTinhLuong = new javax.swing.JButton();
        btnTinhluongALL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QL_LichLamViec");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thong_tin_Lich_Lam_Viec", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setText("IdNV:");

        txtIdnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdnvActionPerformed(evt);
            }
        });

        txtIdcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdclActionPerformed(evt);
            }
        });

        jLabel2.setText("id_ca_lam");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Thu:");

        txtThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThuActionPerformed(evt);
            }
        });

        btnDelete.setText("Nghi phep");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdcl, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdnv, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtThu, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thu", "idNV", "id_ca_lam"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_ca_lam", "He_so_luong", "Gio_bat_dau", "Gio_ket_thuc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idnv", "TenNV", "Luong"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        btnTinhLuong.setText("Tinh luong");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        btnTinhluongALL.setText("Tinh luong tat ca");
        btnTinhluongALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhluongALLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTinhLuong)
                            .addComponent(btnTinhluongALL))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTinhLuong)
                                .addGap(41, 41, 41)
                                .addComponent(btnTinhluongALL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdnvActionPerformed

    private void txtIdclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdclActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        Connection conn = null;
        CallableStatement cstmt = null;
        Statement stmt = null;
        List<lichlamviec> llv = new ArrayList<>();

        String thu = txtThu.getText();
        String idnv = txtIdnv.getText();
        String idcalam = txtIdcl.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/quantridulieu?"

                + "user=root");

            cstmt = conn.prepareCall("{call addlichlamviec(?,?,?)}");

            cstmt.setString(1,thu);
            cstmt.setString(2,idnv);
            cstmt.setString(3,idcalam);

            cstmt.executeQuery();
            
            stmt=conn.createStatement();
        
            String sql="select * from lichlamviec order by thu";
            ResultSet rs = stmt.executeQuery(sql);


            while(rs.next()){
                lichlamviec l = new lichlamviec(rs.getString("thu"),
                        rs.getInt("idnv"),
                        rs.getInt("idcalam")
                        );
                llv.add(l);
            }               
                   

        } catch (Exception ex) { //xử lý ngoại lệ nếu có
            ex.printStackTrace();
        }

        finally {
            //giải phóng tài nguyên khi không sử dụng nữa
            if (stmt != null) {
            try {
            stmt.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            stmt = null;
            }
            
            if (cstmt != null) {
            try {
            cstmt.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            cstmt = null;
            }

            if (conn != null) {
            try {
            conn.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            conn = null;
            }}
        
        tableModel = (DefaultTableModel) jTable1.getModel();
        int rows = tableModel.getRowCount();
        
        if(rows!=0){
            for(int i=rows-1;i>=0;i-- ){
                tableModel.removeRow(i);
            }
        }
        
        for(lichlamviec l : llv){
            System.out.println(l);
            
            tableModel.addRow(new Object[]{
               
               l.getThu(),l.getIdnv(),l.getIdcl()
            });
        }
            
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThuActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        Connection conn = null;
        CallableStatement cstmt = null;
        Statement stmt = null;
        List<lichlamviec> llv = new ArrayList<>();

        String thu = txtThu.getText();
        String idnv = txtIdnv.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/quantridulieu?"

                + "user=root");

            cstmt = conn.prepareCall("{call nghiphep(?,?)}");
            cstmt.setString(1,idnv);
            cstmt.setString(2,thu);
            cstmt.executeQuery();
            
            stmt=conn.createStatement();
        
            String sql="select * from lichlamviec order by thu";
            ResultSet rs = stmt.executeQuery(sql);


            while(rs.next()){
                lichlamviec l = new lichlamviec(rs.getString("thu"),
                        rs.getInt("idnv"),
                        rs.getInt("idcalam")
                        );
                llv.add(l);
            } 

        } catch (Exception ex) { //xử lý ngoại lệ nếu có
            ex.printStackTrace();
        }

        finally {
            //giải phóng tài nguyên khi không sử dụng nữa
            if (stmt != null) {
            try {
            stmt.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            stmt = null;
            }
            
            if (cstmt != null) {
            try {
            cstmt.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            cstmt = null;
            }

            if (conn != null) {
            try {
            conn.close();
            } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
            conn = null;
            }}
        
        tableModel = (DefaultTableModel) jTable1.getModel();
        int rows = tableModel.getRowCount();
        
        if(rows!=0){
            for(int i=rows-1;i>=0;i-- ){
                tableModel.removeRow(i);
            }
        }
        
        for(lichlamviec l : llv){
            System.out.println(l);
            
            tableModel.addRow(new Object[]{
               
               l.getThu(),l.getIdnv(),l.getIdcl()
            });
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        CallableStatement cstmt = null;
        List<tinhluong> tl = new ArrayList<>();

        String idnv = txtIdnv.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/quantridulieu?"

                + "user=root");

            cstmt = conn.prepareCall("{call tinhluong1nguoi(?)}");
            cstmt.setString(1,idnv);           
            
            ResultSet rs1=cstmt.executeQuery();
        
            while(rs1.next()){
                tinhluong t = new tinhluong(rs1.getInt("idnv"),
                    rs1.getString("tennhanvien"),
                    rs1.getDouble("luong")
                );
                tl.add(t);
            }

        } catch (Exception ex) { //xử lý ngoại lệ nếu có
            ex.printStackTrace();
        }

        finally {
            //giải phóng tài nguyên khi không sử dụng nữa
            if (cstmt != null) {
                try {
                    cstmt.close();
                } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
                cstmt = null;
            }

            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
                conn = null;
            }}
        
        tableModel = (DefaultTableModel) jTable3.getModel();
        int rows = tableModel.getRowCount();
        
        if(rows!=0){
            for(int i=rows-1;i>=0;i-- ){
                tableModel.removeRow(i);
            }
        }
        
        for(tinhluong t : tl){
            System.out.println(t);
            
            tableModel.addRow(new Object[]{
               
               t.getIdnv(),t.getTennv(),t.getLuong()
            });
        }
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnTinhluongALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhluongALLActionPerformed
        // TODO add your handling code here:
        
        Connection conn = null;
        CallableStatement cstmt = null;
        Statement stmt=null;
        List<tinhluong> tl = new ArrayList<>();

        String idnv = txtIdnv.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/quantridulieu?"

                + "user=root");
            
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from nhanvien");
            int e=1;
            
            while(rs.next()){
                cstmt = conn.prepareCall("{call tinhluong1nguoi(?)}");
                cstmt.setInt(1,e);      
            
                ResultSet rs1=cstmt.executeQuery();

                while(rs1.next()){
                    tinhluong t = new tinhluong(rs1.getInt("idnv"),
                        rs1.getString("tennhanvien"),
                        rs1.getDouble("luong")
                    );
                    tl.add(t);
                }
                e++;
            }
            

        } catch (Exception ex) { //xử lý ngoại lệ nếu có
            ex.printStackTrace();
        }

        finally {
            //giải phóng tài nguyên khi không sử dụng nữa
            if (cstmt != null) {
                try {
                    cstmt.close();
                } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
                cstmt = null;
            }

            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException sqlEx) { } //đoạn mã xử lý ng/lệ
                conn = null;
            }}
        
        tableModel = (DefaultTableModel) jTable3.getModel();
        int rows = tableModel.getRowCount();
        
        if(rows!=0){
            for(int i=rows-1;i>=0;i-- ){
            tableModel.removeRow(i);
        }
        }
        
        for(tinhluong t : tl){
            System.out.println(t);
            
            tableModel.addRow(new Object[]{
               
               t.getIdnv(),t.getTennv(),t.getLuong()
            });
        }
    }//GEN-LAST:event_btnTinhluongALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Lich_Lam_Viec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Lich_Lam_Viec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Lich_Lam_Viec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Lich_Lam_Viec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quan_Ly_Lich_Lam_Viec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnTinhluongALL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtIdcl;
    private javax.swing.JTextField txtIdnv;
    private javax.swing.JTextField txtThu;
    // End of variables declaration//GEN-END:variables
}
